swagger: "2.0"
info:
  version: "0.0.1"
  title: productService
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /products:
    # binds a127 app logic to a route
    x-swagger-router-controller: hello_world
    get:
      description: Return array of products
      # used as the method name of the controller
      
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/getProductsListResponse"
            
  /products/{productId}:
    get:
      description: Return single product or error with status 404 if product does not exist
      parameters:
        - in: path
          name: productId
          schema:
            type: string
          required: true
          description: The user id
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/getProductsByIdSuccessResponse"
        "404":
          description: Not found
          schema:
            $ref: "#/definitions/getProductsByIdErrorResponse"
            
          
  
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  product:
    required:
      - id
      - count
      - description
      - price
      - title
    properties:
      id:
        type: string
      count:
        type: number
      description:
        type: string
      price:
        type: integer
      title:
        type: string
        
  getProductsListResponse:
    properties:
      products:
        type: array
        items:
          $ref: "#/definitions/product"
  
  getProductsByIdSuccessResponse:
    properties:
      products:
        type: object
        $ref: "#/definitions/product"
        
  getProductsByIdErrorResponse:
    required:
      - status
      - error
    properties:
      status:
        type: integer
      error:
        type: string